In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
RAW_DATA_PATH = "../data/raw/"

files = os.listdir(RAW_DATA_PATH)
print(files)

['salesdaily.csv', 'saleshourly.csv', 'salesmonthly.csv', 'salesweekly.csv']

In [3]:
df_hourly = pd.read_csv(RAW_DATA_PATH + "saleshourly.csv")

In [4]:
print(df_hourly)

                 datum  M01AB  M01AE  N02BA  N02BE  N05B  N05C  R03  R06  \
0        1/2/2014 8:00   0.00   0.67    0.4    2.0   0.0   0.0  0.0  1.0
1        1/2/2014 9:00   0.00   0.00    1.0    0.0   2.0   0.0  0.0  0.0
2       1/2/2014 10:00   0.00   0.00    0.0    3.0   2.0   0.0  0.0  0.0
3       1/2/2014 11:00   0.00   0.00    0.0    2.0   1.0   0.0  0.0  0.0
4       1/2/2014 12:00   0.00   2.00    0.0    5.0   2.0   0.0  0.0  0.0
...                ...    ...    ...    ...    ...   ...   ...  ...  ...
50527  10/8/2019 15:00   0.00   0.40    0.0   11.3   1.0   0.0  0.0  0.0
50528  10/8/2019 16:00   0.33   0.00    0.0    1.0   2.0   0.0  0.0  0.0
50529  10/8/2019 17:00   0.00   0.00    0.0    1.0   2.0   0.0  1.0  0.0
50530  10/8/2019 18:00   0.00   0.00    0.0    9.0   0.0   0.0  0.0  0.0
50531  10/8/2019 19:00   0.00   0.33    0.0    8.0   1.0   0.0  1.0  0.0

       Year  Month  Hour Weekday Name
0      2014      1     8     Thursday
1      2014      1     9     Thursday
2      2014      1    10     Thursday
3      2014      1    11     Thursday
4      2014      1    12     Thursday
...     ...    ...   ...          ...
50527  2019     10    15      Tuesday
50528  2019     10    16      Tuesday
50529  2019     10    17      Tuesday
50530  2019     10    18      Tuesday
50531  2019     10    19      Tuesday

[50532 rows x 13 columns]

In [5]:
print(df_hourly.shape)
print(df_hourly.dtypes)

df_hourly.head()

(50532, 13)
datum               str
M01AB           float64
M01AE           float64
N02BA           float64
N02BE           float64
N05B            float64
N05C            float64
R03             float64
R06             float64
Year              int64
Month             int64
Hour              int64
Weekday Name        str
dtype: object

,datum,M01AB,M01AE,N02BA,N02BE,N05B,N05C,R03,R06,Year,Month,Hour,Weekday Name
0,1/2/2014 8:00,0.0,0.67,0.4,2.0,0.0,0.0,0.0,1.0,2014,1,8,Thursday
1,1/2/2014 9:00,0.0,0.00,1.0,0.0,2.0,0.0,0.0,0.0,2014,1,9,Thursday
2,1/2/2014 10:00,0.0,0.00,0.0,3.0,2.0,0.0,0.0,0.0,2014,1,10,Thursday
3,1/2/2014 11:00,0.0,0.00,0.0,2.0,1.0,0.0,0.0,0.0,2014,1,11,Thursday
4,1/2/2014 12:00,0.0,2.00,0.0,5.0,2.0,0.0,0.0,0.0,2014,1,12,Thursday

In [6]:
# Load all four datasets
df_hourly = pd.read_csv(RAW_DATA_PATH + "saleshourly.csv")
df_daily = pd.read_csv(RAW_DATA_PATH + "salesdaily.csv")
df_weekly = pd.read_csv(RAW_DATA_PATH + "salesweekly.csv")
df_monthly = pd.read_csv(RAW_DATA_PATH + "salesmonthly.csv")

# Quick shape check on all files
datasets = {
    "hourly": df_hourly,
    "daily": df_daily,
    "weekly": df_weekly,
    "monthly": df_monthly
}

for name,df in datasets.items():
    print(f"{name}: {df.shape}")

hourly: (50532, 13)
daily: (2106, 13)
weekly: (302, 9)
monthly: (70, 9)

In [7]:
df_hourly.info()

<class 'pandas.DataFrame'>
RangeIndex: 50532 entries, 0 to 50531
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   datum         50532 non-null  str
 1   M01AB         50532 non-null  float64
 2   M01AE         50532 non-null  float64
 3   N02BA         50532 non-null  float64
 4   N02BE         50532 non-null  float64
 5   N05B          50532 non-null  float64
 6   N05C          50532 non-null  float64
 7   R03           50532 non-null  float64
 8   R06           50532 non-null  float64
 9   Year          50532 non-null  int64
 10  Month         50532 non-null  int64
 11  Hour          50532 non-null  int64
 12  Weekday Name  50532 non-null  str
dtypes: float64(8), int64(3), str(2)
memory usage: 5.0 MB

In [8]:
df_hourly.describe()

,M01AB,M01AE,N02BA,N02BE,N05B,N05C,R03,R06,Year,Month,Hour
count,50532.000000,50532.000000,50532.000000,50532.000000,50532.000000,50532.000000,50532.000000,50532.000000,50532.000000,50532.000000,50532.000000
mean,0.209787,0.162365,0.161723,1.246842,0.368989,0.024736,0.229732,0.120870,2016.401409,6.344811,11.500475
std,0.556003,0.416109,0.453211,2.387392,0.930934,0.217871,1.240513,0.391999,1.664444,3.385761,6.921706
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2014.000000,1.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2015.000000,3.000000,6.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2016.000000,6.000000,12.000000
75%,0.000000,0.000000,0.000000,1.875000,0.000000,0.000000,0.000000,0.000000,2018.000000,9.000000,17.000000
max,7.000000,6.000000,6.500000,29.000000,15.000000,6.000000,25.000000,5.000000,2019.000000,12.000000,23.000000

In [9]:
df_hourly.head()

,datum,M01AB,M01AE,N02BA,N02BE,N05B,N05C,R03,R06,Year,Month,Hour,Weekday Name
0,1/2/2014 8:00,0.0,0.67,0.4,2.0,0.0,0.0,0.0,1.0,2014,1,8,Thursday
1,1/2/2014 9:00,0.0,0.00,1.0,0.0,2.0,0.0,0.0,0.0,2014,1,9,Thursday
2,1/2/2014 10:00,0.0,0.00,0.0,3.0,2.0,0.0,0.0,0.0,2014,1,10,Thursday
3,1/2/2014 11:00,0.0,0.00,0.0,2.0,1.0,0.0,0.0,0.0,2014,1,11,Thursday
4,1/2/2014 12:00,0.0,2.00,0.0,5.0,2.0,0.0,0.0,0.0,2014,1,12,Thursday

In [10]:
def load_dataset(filename):
    filepath = os.path.join(RAW_DATA_PATH, filename)

    if not os.path.exists(filepath):
        raise FileNotFoundError(f"File not found: {filepath}")

    df = pd.read_csv(filepath)
    print(f" Loaded {filename}: {df.shape[0]} rows, {df.shape[1]} columns")

    return df

In [11]:
df_hourly = load_dataset("saleshourly.csv")

 Loaded saleshourly.csv: 50532 rows, 13 columns

In [12]:
# Load all datasets using our function
df_hourly  = load_dataset("saleshourly.csv")
df_daily   = load_dataset("salesdaily.csv")
df_weekly  = load_dataset("salesweekly.csv")
df_monthly = load_dataset("salesmonthly.csv")

 Loaded saleshourly.csv: 50532 rows, 13 columns
 Loaded salesdaily.csv: 2106 rows, 13 columns
 Loaded salesweekly.csv: 302 rows, 9 columns
 Loaded salesmonthly.csv: 70 rows, 9 columns

In [13]:
def profile_dataset(df, name):
    """
    Print basic profile of dataframe.

    Args:
        df (pd.DataFrame): Dataset to profile
        name (str): Name label for display
    """
    print(f"\n{'='*50}")
    print(f"DATASET: {name}")
    print(f"{'='*50}")
    print(f"Shape :{df.shape}")
    print(f"Date range : {df['datum'].min()} -> {df['datum'].max()}")
    print(f"Null Values: {df.isnull().sum().sum()}")
    print(f"Duplicates: {df.duplicated().sum()}")
    print(f"{'='*50}")

#Profile all datasets
for name,df in datasets.items():
    profile_dataset(df, name)

==================================================
DATASET: hourly
==================================================
Shape :(50532, 13)
Date range : 1/1/2015 0:00 -> 9/9/2019 9:00
Null Values: 0
Duplicates: 0
==================================================

==================================================
DATASET: daily
==================================================
Shape :(2106, 13)
Date range : 1/1/2015 -> 9/9/2019
Null Values: 0
Duplicates: 0
==================================================

==================================================
DATASET: weekly
==================================================
Shape :(302, 9)
Date range : 1/1/2017 -> 9/9/2018
Null Values: 0
Duplicates: 0
==================================================

==================================================
DATASET: monthly
==================================================
Shape :(70, 9)
Date range : 2014-01-31 -> 2019-10-31
Null Values: 0
Duplicates: 0
==================================================

In [14]:
for name,df in datasets.items():
    zeros = (df[['M01AB', 'M01AE',	'N02BA',	'N02BE',	'N05B',	'N05C',	'R03',	'R06']] == 0).sum().sum()
    print(f"{name}: {zeros} zero values in drug columns")

hourly: 337875 zero values in drug columns
daily: 2393 zero values in drug columns
weekly: 36 zero values in drug columns
monthly: 7 zero values in drug columns

In [15]:
drug_cols = ['M01AB', 'M01AE',	'N02BA',	'N02BE',	'N05B',	'N05C',	'R03',	'R06']

all_zero_rows = df_hourly[(df_hourly[drug_cols]==0).all(axis=1)]
print(f"Rows where ALL drugs are zero: {len(all_zero_rows)}")
print(all_zero_rows[['datum','Hour','Weekday Name']].head(20))

Rows where ALL drugs are zero: 23944
             datum  Hour Weekday Name
6   1/2/2014 14:00    14     Thursday
7   1/2/2014 15:00    15     Thursday
8   1/2/2014 16:00    16     Thursday
9   1/2/2014 17:00    17     Thursday
10  1/2/2014 18:00    18     Thursday
11  1/2/2014 19:00    19     Thursday
12  1/2/2014 20:00    20     Thursday
13  1/2/2014 21:00    21     Thursday
14  1/2/2014 22:00    22     Thursday
15  1/2/2014 23:00    23     Thursday
16   1/3/2014 0:00     0       Friday
17   1/3/2014 1:00     1       Friday
18   1/3/2014 2:00     2       Friday
19   1/3/2014 3:00     3       Friday
20   1/3/2014 4:00     4       Friday
21   1/3/2014 5:00     5       Friday
22   1/3/2014 6:00     6       Friday
37  1/3/2014 21:00    21       Friday
38  1/3/2014 22:00    22       Friday
39  1/3/2014 23:00    23       Friday

In [16]:
zero_by_hour = all_zero_rows.groupby('Hour').size().sort_index()
print(zero_by_hour)

Hour
0     2105
1     2105
2     2105
3     2105
4     2105
5     2105
6     2105
7     1790
8      357
9      208
10     134
11     125
12     124
13     156
14     220
15     230
16     269
17     245
18     181
19     147
20     179
21     700
22    2041
23    2103
dtype: int64

In [17]:
zero_by_weekday = all_zero_rows.groupby('Weekday Name').size().sort_index(ascending=False)
print(zero_by_weekday)

Weekday Name
Wednesday    3290
Tuesday      3278
Thursday     3362
Sunday       3921
Saturday     3465
Monday       3329
Friday       3299
dtype: int64